[tool.poetry]
name = "cadquery-fused-assembly"
version = "0.1.0"
description = ""
authors = ["Mate Kovacs <mkovaxx@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
cadquery = "2.3.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
